# Generated by Django 3.1.2 on 2020-10-20 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('subject_desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=100)),
                ('topic_desc', models.CharField(blank=True, max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSubtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(blank=True, max_length=100)),
                ('subtopic_desc', models.CharField(blank=True, max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subjecttopic')),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicLearningUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_url', models.CharField(blank=True, max_length=255)),
                ('learning_url_desc', models.CharField(blank=True, max_length=255)),
                ('learning_url_section_name', models.CharField(blank=True, max_length=255)),
                ('learning_url_code_link', models.CharField(blank=True, max_length=255)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.topicsubtopic')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.CharField(blank=True, max_length=255)),
                ('project_desc', models.TextField(blank=True, max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_url', models.CharField(blank=True, max_length=255)),
                ('free_ind', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('online_ind', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('course_desc', models.TextField(blank=True, max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('subject_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subjectproject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningUrlVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('learning_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subjectproject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('subject_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subjectproject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
