# Generated by Django 3.1.2 on 2020-10-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(blank=True, max_length=100)),
                ('subtopic_desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='CourseVote',
            new_name='Course_Vote',
        ),
        migrations.RenameModel(
            old_name='LearningUrlVote',
            new_name='Learning_Url_Vote',
        ),
        migrations.RenameModel(
            old_name='ProjectVote',
            new_name='Project_Vote',
        ),
        migrations.RenameModel(
            old_name='SubjectCourse',
            new_name='Subject_Course',
        ),
        migrations.RenameModel(
            old_name='SubjectProject',
            new_name='Subject_Project',
        ),
        migrations.RenameModel(
            old_name='SubjectTopic',
            new_name='Subject_Topic',
        ),
        migrations.RenameModel(
            old_name='SubtopicLearningUrl',
            new_name='Subtopic_Learning_Url',
        ),
        migrations.DeleteModel(
            name='TopicSubtopic',
        ),
        migrations.AddField(
            model_name='topic_subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.subject_topic'),
        ),
        migrations.AlterField(
            model_name='subtopic_learning_url',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cll.topic_subtopic'),
        ),
    ]
